### ISSUE TITLE
OCP4 Migration - Test on silver (ocp4) new storage type with production load

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#130]
**Describe the issue**
This is a preparation task for OCP4 migration.
Coming to ocp4 we have new storage types, while currently on ocp3 SSO is still using gluster file. So before migrating over the prod instance, we need to test with production load with the new storage type first. 

#### Preparation need:
- [x] have a SSO pipeline and a sandbox instance setup in ocp4
- [x] setup k6 in an sandbox namespace
- [x] backup container to restore prod DB to sandbox SSO (***note that db cred has to match for restoring DB***)

**Definition of done**
- test with production like load on silver using k6 testing

**Comment by ShellyXueHan** [comment]
## Results:

### Volume mount:
df shows very close status on the DB data path where volume is mounted. Following is the status after restoring the same DB backup.
```shell
# in ocp3 gluster-block:
/dev/mapper/mpathcg                     5232640  1188876   4043764  23% /home/postgres/pgdata

# in ocp4 netapp-block-standard:
/dev/mapper/3600a098038314354633f506d705a6154   5232640   1428660   3803980  28% /home/postgres/pgdata
```

### Patroni usage:
Common patroni commands, such as `patronictl failover` run successfully within short time period.


### K6 load test result:
With the same k6 load test, we are able to reproduce the issue on ocp4 sandbox SSO (error message as follows). Thus we consider this is producing similar amount of DB connection load in the patroni statefulset.

```
22:18:57,163 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread--p12-t1) ISPN000136: Error executing command PutKeyValueCommand on Cache 'actionTokens', writing keys [d58592e9-e813-43ba-bbaa-efa1706b67fd]: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 24722 from sso-sbox-148-1-p4ggn
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.remoting.transport.impl.MultiTargetRequest.onTimeout(MultiTargetRequest.java:167)
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:87)
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:22)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

22:18:57,165 WARN  [org.keycloak.services] (default task-97) KC-SERVICES0013: Failed authentication: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 24722 from sso-sbox-148-1-p4ggn
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:259)
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.cache.impl.CacheImpl.executeCommandAndCommitIfNeeded(CacheImpl.java:1915)
```

Here is the resource consumption level of *patroni cluster primary pod* during load test:
- CPU: 0.262 cores (before load test 0.091)
- Memory: 1.28 GiB (before load test 940 MiB)

Compared to ocp3 load test figures:
- CPU: 0.289 cores (before load test 0.062)
- Memory: 448 MiB (before load test 160 MiB)

The increase of resource usage after load test are similar between the two primary pods. We would say the new storage type `netapp-block-standard` works fine with expected SSO service production load. Still we will need to keep monitoring storage after migration is complete.

**Comment by ShellyXueHan** [comment]
@patricksimonian @arcshiftsolutions please see in comments on the testing I've done for moving to new PVC storage class. Anything else you can think of?
