### ISSUE TITLE
k6 test update

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#132]
**Describe the issue**
As we still cannot reproduce production load with k6 tests, need to explore some different ways to test sso and create user sessions and cache.
- test request to different realms
- test increasing concurrent sessions
- test with more users

**Definition of done**
- able to reproduce load on sso pods

**Comment by ShellyXueHan** [comment]
### Update:
- Currently running test over multiple realms. Will need more test run to verify if multiple realms helps to reproduce the load issue.
- Code updates here: https://github.com/bcgov/ocp-sso/pull/133

**Comment by ShellyXueHan** [comment]
### Update:
k6 test is now able to reproduce production sso resource issues with the following config:
- sso resource config set to previous level: `CPU: 500 millicores to 1 core and Memory: 512 MiB to 1 GiB`
- db statefulset reminds the same
- k6 testings with `token invalidation` disabled
- k6 test cases with 100 concurrent virtual users, running for at least 10 mins

### error logs:
here are the sso error logs which is similar to the ones we got from prod sso:
```
23:21:58,438 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread--p5-t1) ISPN000136: Error executing command RemoveExpiredCommand on Cache 'work', writing keys [fca45be4-2e6b-47a7-855a-9a5e7ad0736f]: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 66981 from sso-sbox-125-5-9qdsv
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.remoting.transport.impl.MultiTargetRequest.onTimeout(MultiTargetRequest.java:167)
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:87)
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:22)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

23:21:58,439 WARN  [org.infinispan.expiration.impl.ClusterExpirationManager] (expiration-thread--p26-t1) ISPN000026: Caught exception purging data container!: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 66981 from sso-sbox-125-5-9qdsv
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.remoting.transport.impl.MultiTargetRequest.onTimeout(MultiTargetRequest.java:167)
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:87)
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:22)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### k6 test results when error occurs:
```
    ✗ Token endpoint successfully
     ↳  99% — ✓ 2424 / ✗ 22
    ✗ Token Refresh endpoint successfully
     ↳  99% — ✓ 2424 / ✗ 22
    ✓ SA Client auth successfully

    █ Client APIs

      █ Create clients

        ✓ SA Client POST-Create successfully

      █ Get clients

        ✗ SA Client GET successfully
         ↳  99% — ✓ 2444 / ✗ 2

      █ Delete clients

        ✗ SA Client DELETE successfully
         ↳  99% — ✓ 2437 / ✗ 9

    authentication_successful...: 100.00% ✓ 4848  ✗ 0    
    checks......................: 99.62%  ✓ 14621 ✗ 55   
    data_received...............: 74 MB   241 kB/s
    data_sent...................: 20 MB   66 kB/s
    errors......................: 100.00% ✓ 44    ✗ 0    
    group_duration..............: avg=2.14s    min=1s      med=1.39s    max=12.69s   p(90)=4.2s     p(95)=5.01s   
    http_req_blocked............: avg=1.33ms   min=1.94µs  med=5.65µs   max=225.3ms  p(90)=11.76µs  p(95)=19.02µs 
    http_req_connecting.........: avg=322.37µs min=0s      med=0s       max=55.26ms  p(90)=0s       p(95)=0s      
    http_req_duration...........: avg=903.37ms min=3.32ms  med=383.69ms max=30.78s   p(90)=2.2s     p(95)=2.98s   
    http_req_receiving..........: avg=440.04µs min=57.23µs med=190.57µs max=327.84ms p(90)=346.42µs p(95)=427.09µs
    http_req_sending............: avg=29.3µs   min=11.27µs med=25.67µs  max=1.23ms   p(90)=43.1µs   p(95)=52.73µs 
    http_req_tls_handshaking....: avg=856.7µs  min=0s      med=0s       max=156.14ms p(90)=0s       p(95)=0s      
    http_req_waiting............: avg=902.9ms  min=3.07ms  med=383.31ms max=30.78s   p(90)=2.2s     p(95)=2.98s   
    http_reqs...................: 14676   47.530526/s
    iteration_duration..........: avg=12.47s   min=7.56s   med=11.2s    max=1m0s     p(90)=15.23s   p(95)=19.21s  
    iterations..................: 2446    7.921754/s
    vus.........................: 17      min=17  max=100
    vus_max.....................: 100     min=100 max=100
```

**Comment by ShellyXueHan** [comment]
https://github.com/bcgov/ocp-sso/pull/133
